[package]
name = "whitebox"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.19.1", features = [
    "std",
    "tui",
    "train",
    "vision",
    "wgpu",
    "fusion",
], default-features = false }
image = "0.25.9"
num-traits = "0.2.19"

[dev-dependencies]
nalgebra = "0.34.1"
