[package]
name = "whitebox"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", features = [
    "std",
    "train",
    "vision",
    "wgpu",
    "fusion",
], default-features = false }
burn-import = { version = "0.20.1", default-features = false, features = [
    "pytorch",
] }
image = "0.25.9"
ndarray = "0.17.2"
num-traits = "0.2.19"
scirs2-vision = "0.1.3"

[dev-dependencies]
nalgebra = "0.34.1"

[features]
rocm = ["burn/rocm"]
